[project]
name = "code-analysis"
version = "0.1.0"
description = "Code analysis tool using CrewAI"
requires-python = ">=3.12,<3.13"
dependencies = [
    "crewai>=0.80.0",
    "openai>=1.3.0",
    "python-dotenv>=1.0.0",
    "loguru>=0.7.2",
    "pydantic>=2.5.2",
    "black>=23.11.0",
    "tomli>=2.0.1"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true
